##### Loading and Inspecting the DataSet

In [46]:
from pandas import pandas as pd

data_set = "data\Economic & Livelihood Impact\war_economic_impact_dataset.csv"

df = pd.read_csv(data_set, header=0)
df.head()

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented
0,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,7.49,21.78,14.29,...,97.41,170.33,106957216228,209054555175,15.50,27.09,High,food,10.50,No
1,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.18,23.00,14.82,...,73.68,41.97,304164881098,585915946162,11.95,34.76,Dominant,fuel,19.31,No
2,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,12.70,36.46,23.76,...,69.35,53.91,484822729254,1666739121273,38.18,90.00,Moderate,"water, weapons, currency",298.95,No
3,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,14.06,17.83,3.77,...,36.92,48.51,71321188262,250015887113,12.24,36.42,Moderate,"currency, medicine, weapons",15.44,No
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,5.38,5.98,0.59,...,52.62,31.32,156180178536,361238241031,31.89,74.86,Dominant,medicine,443.61,Yes

In [38]:
df.shape[0], df.shape[1]

(100000, 28)

In [19]:
df.columns.tolist()

['Conflict_Name',
 'Conflict_Type',
 'Region',
 'Start_Year',
 'End_Year',
 'Status',
 'Primary_Country',
 'Pre_War_Unemployment_%',
 'During_War_Unemployment_%',
 'Unemployment_Spike_Percentage_Points',
 'Most_Affected_Sector',
 'Youth_Unemployment_Change_%',
 'Pre_War_Poverty_Rate_%',
 'During_War_Poverty_Rate_%',
 'Extreme_Poverty_Rate_%',
 'Food_Insecurity_Rate_%',
 'Households_Fallen_Into_Poverty_Estimate',
 'GDP_Change_%',
 'Inflation_Rate_%',
 'Currency_Devaluation_%',
 'Cost_of_War_USD',
 'Estimated_Reconstruction_Cost_USD',
 'Informal_Economy_Size_Pre_War_%',
 'Informal_Economy_Size_During_War_%',
 'Black_Market_Activity_Level',
 'Primary_Black_Market_Goods',
 'Currency_Black_Market_Rate_Gap_%',
 'War_Profiteering_Documented']

In [17]:
df.describe()

,Start_Year,End_Year,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,Youth_Unemployment_Change_%,Pre_War_Poverty_Rate_%,During_War_Poverty_Rate_%,Extreme_Poverty_Rate_%,Food_Insecurity_Rate_%,Households_Fallen_Into_Poverty_Estimate,GDP_Change_%,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Currency_Black_Market_Rate_Gap_%
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,1.000000e+05,1.000000e+05,100000.000000,100000.000000,100000.000000
mean,1999.401340,2009.039940,9.017027,22.625199,13.608182,17.686763,17.518820,29.077186,14.553542,20.351211,1.597617e+05,-31.614770,69.945965,87.580570,2.507148e+11,6.895004e+11,25.002639,51.783920,126.181130
std,29.957153,30.552183,3.458406,13.818295,11.960175,15.678211,7.217439,13.000781,7.487060,9.790643,9.355617e+05,18.120243,35.045196,55.632842,1.436970e+11,4.471766e+11,8.648263,21.266786,156.324982
min,1939.000000,1945.000000,3.000000,3.360000,0.320000,0.360000,5.000000,5.400000,1.840000,3.100000,1.000000e+00,-85.000000,0.030000,0.030000,1.001111e+09,1.617224e+09,10.000000,12.140000,0.000000
25%,1996.000000,2011.000000,6.030000,12.780000,5.330000,6.860000,11.260000,20.030000,9.270000,13.490000,5.710750e+03,-42.210000,42.710000,45.110000,1.266235e+11,3.239366e+11,17.520000,34.420000,9.330000
50%,2011.000000,2026.000000,9.020000,19.480000,10.220000,13.245000,17.520000,27.630000,13.200000,18.800000,2.210450e+04,-29.700000,69.290000,76.680000,2.501850e+11,6.367629e+11,25.010000,49.190000,18.760000
75%,2022.000000,2026.000000,12.000000,28.800000,17.890000,23.270000,23.790000,35.290000,18.250000,25.200000,8.439800e+04,-17.337500,94.800000,120.460000,3.750452e+11,9.934733e+11,32.490000,67.820000,241.432500
max,2025.000000,2026.000000,15.000000,89.400000,74.470000,108.710000,30.000000,98.000000,68.490000,86.320000,9.928908e+07,-5.000000,295.560000,528.400000,4.999992e+11,1.997802e+12,40.000000,90.000000,500.000000

In [24]:
df.dtypes

Conflict_Name                               object
Conflict_Type                               object
Region                                      object
Start_Year                                   int64
End_Year                                     int64
Status                                      object
Primary_Country                             object
Pre_War_Unemployment_%                     float64
During_War_Unemployment_%                  float64
Unemployment_Spike_Percentage_Points       float64
Most_Affected_Sector                        object
Youth_Unemployment_Change_%                float64
Pre_War_Poverty_Rate_%                     float64
During_War_Poverty_Rate_%                  float64
Extreme_Poverty_Rate_%                     float64
Food_Insecurity_Rate_%                     float64
Households_Fallen_Into_Poverty_Estimate      int64
GDP_Change_%                               float64
Inflation_Rate_%                           float64
Currency_Devaluation_%                     float64
Cost_of_War_USD                              int64
Estimated_Reconstruction_Cost_USD            int64
Informal_Economy_Size_Pre_War_%            float64
Informal_Economy_Size_During_War_%         float64
Black_Market_Activity_Level                 object
Primary_Black_Market_Goods                  object
Currency_Black_Market_Rate_Gap_%           float64
War_Profiteering_Documented                 object
dtype: object

In [39]:
df.isnull().sum()

Conflict_Name                              0
Conflict_Type                              0
Region                                     0
Start_Year                                 0
End_Year                                   0
Status                                     0
Primary_Country                            0
Pre_War_Unemployment_%                     0
During_War_Unemployment_%                  0
Unemployment_Spike_Percentage_Points       0
Most_Affected_Sector                       0
Youth_Unemployment_Change_%                0
Pre_War_Poverty_Rate_%                     0
During_War_Poverty_Rate_%                  0
Extreme_Poverty_Rate_%                     0
Food_Insecurity_Rate_%                     0
Households_Fallen_Into_Poverty_Estimate    0
GDP_Change_%                               0
Inflation_Rate_%                           0
Currency_Devaluation_%                     0
Cost_of_War_USD                            0
Estimated_Reconstruction_Cost_USD          0
Informal_Economy_Size_Pre_War_%            0
Informal_Economy_Size_During_War_%         0
Black_Market_Activity_Level                0
Primary_Black_Market_Goods                 0
Currency_Black_Market_Rate_Gap_%           0
War_Profiteering_Documented                0
dtype: int64

##### Data Wrangling & Feature Engineering

In [47]:
# The Data overall is already clean with there being zero null or NA rows
# However, a few changes can be made with the data set. Such as changing the "War Profiteering Documented" 
# Result of yes/no to 1/0. And changing "Black Market Activity Level" from "Low, Moderate, High, Dominant"
# To "1, 2, 3, 4".


df["War_Profiteering_Documented"] = df["War_Profiteering_Documented"].str.lower().map({"yes" : 1, "no" : 0})
df["War_Profiteering_Documented"]

0        0
1        0
2        0
3        0
4        1
        ..
99995    1
99996    0
99997    1
99998    1
99999    0
Name: War_Profiteering_Documented, Length: 100000, dtype: int64

In [48]:
# df.isnull().sum()
bmal = {"low" : 1, "moderate" : 2, "high" : 3, "dominant" : 4}
df["Black_Market_Activity_Level"] = df["Black_Market_Activity_Level"].str.lower().map(bmal)
df["Black_Market_Activity_Level"]

0        3
1        4
2        2
3        2
4        4
        ..
99995    4
99996    1
99997    1
99998    4
99999    3
Name: Black_Market_Activity_Level, Length: 100000, dtype: int64

In [65]:
# display(df.sort_values(["Conflict_Name", "Conflict_Type", "Region"]))
df["Duration_in_years"] = df["End_Year"] - df["Start_Year"]
df["Informal_Economy_Size_Spike_%"] = df["Informal_Economy_Size_During_War_%"] - df["Informal_Economy_Size_Pre_War_%"]
df["Reconstruction_Cost_Ratio_USD"] = df["Estimated_Reconstruction_Cost_USD"] / df["Cost_of_War_USD"]
df["Poverty_Rate_Spike_%"] = df["During_War_Poverty_Rate_%"] - df["Pre_War_Poverty_Rate_%"]
display(df.sort_values(["Conflict_Name", "Conflict_Type", "Region"]))
print("New columns added: Duraction in years, Informal Economy Size Spike %," \
" Reconstruction Cost Ratio USD, and Poverty Rate Spike")

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented,Duration_in_years,Informal_Economy_Size_Spike_Percentage,Informal_Economy_Size_Spike_%,Reconstruction_Cost_Ratio_USD,Poverty_Rate_Spike_%
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,5.38,5.98,0.59,...,74.86,4,medicine,443.61,1,20,42.97,42.97,2.312958,0.60
8,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,8.97,14.99,6.02,...,53.47,3,"water, fuel, food",364.11,1,20,20.62,20.62,3.180339,5.58
10,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,11.29,20.72,9.43,...,90.00,1,"currency, medicine",316.55,0,20,53.08,53.08,1.732757,6.96
16,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,11.42,29.84,18.41,...,29.73,4,currency,10.44,0,20,8.92,8.92,3.556501,14.05
28,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,14.40,40.21,25.81,...,83.71,2,weapons,81.31,1,20,49.30,49.30,2.273819,17.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99952,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,9.79,50.63,40.85,...,42.19,4,fuel,7.93,0,11,26.61,26.61,3.260221,31.13
99955,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,9.39,28.79,19.40,...,64.41,4,"medicine, water, currency",282.67,1,11,31.04,31.04,2.765353,19.30
99968,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,9.58,47.37,37.79,...,90.00,3,"currency, weapons, food",4.93,1,11,54.56,54.56,3.604257,19.64
99973,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,10.50,33.67,23.17,...,48.91,4,"medicine, weapons, food",16.10,1,11,13.47,13.47,1.731680,18.92
99974,Yemen Civil War,Civil War,Middle East,2015,2026,Ongoing,Yemen,9.28,37.52,28.23,...,75.05,4,weapons,450.94,1,11,42.01,42.01,2.175207,17.88

New columns added: Duraction in years, Informal Economy Size Spike %, Reconstruction Cost Ratio USD, and Poverty Rate Spike

In [72]:
df.insert(5, 'Duration_in_years', df.pop('Duration_in_years'))
df.insert(28, 'Informal_Economy_Size_Spike_%', df.pop('Informal_Economy_Size_Spike_%'))
df.insert(25, 'Reconstruction_Cost_Ratio_USD', df.pop('Reconstruction_Cost_Ratio_USD'))
df.insert(15, 'Poverty_Rate_Spike_%', df.pop('Poverty_Rate_Spike_%'))

display(df.sort_values(["Conflict_Name", "Conflict_Type", "Region"]))

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Duration_in_years,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,...,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Reconstruction_Cost_Ratio_USD,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Informal_Economy_Size_Spike_%,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented,Informal_Economy_Size_Spike_Percentage
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,20,Resolved,Afghanistan,5.38,5.98,...,361238241031,31.89,2.312958,74.86,4,42.97,medicine,443.61,1,42.97
8,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,20,Resolved,Afghanistan,8.97,14.99,...,387319415238,32.85,3.180339,53.47,3,20.62,"water, fuel, food",364.11,1,20.62
10,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,20,Resolved,Afghanistan,11.29,20.72,...,210849300968,36.92,1.732757,90.00,1,53.08,"currency, medicine",316.55,0,53.08
16,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,20,Resolved,Afghanistan,11.42,29.84,...,69838115333,20.81,3.556501,29.73,4,8.92,currency,10.44,0,8.92
28,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,20,Resolved,Afghanistan,14.40,40.21,...,610547895641,34.41,2.273819,83.71,2,49.30,weapons,81.31,1,49.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99952,Yemen Civil War,Civil War,Middle East,2015,2026,11,Ongoing,Yemen,9.79,50.63,...,21170325214,15.58,3.260221,42.19,4,26.61,fuel,7.93,0,26.61
99955,Yemen Civil War,Civil War,Middle East,2015,2026,11,Ongoing,Yemen,9.39,28.79,...,116297684894,33.37,2.765353,64.41,4,31.04,"medicine, water, currency",282.67,1,31.04
99968,Yemen Civil War,Civil War,Middle East,2015,2026,11,Ongoing,Yemen,9.58,47.37,...,853141563250,35.44,3.604257,90.00,3,54.56,"currency, weapons, food",4.93,1,54.56
99973,Yemen Civil War,Civil War,Middle East,2015,2026,11,Ongoing,Yemen,10.50,33.67,...,731270041825,35.44,1.731680,48.91,4,13.47,"medicine, weapons, food",16.10,1,13.47
99974,Yemen Civil War,Civil War,Middle East,2015,2026,11,Ongoing,Yemen,9.28,37.52,...,553084707317,33.04,2.175207,75.05,4,42.01,weapons,450.94,1,42.01

In [73]:
df.columns.tolist()

['Conflict_Name',
 'Conflict_Type',
 'Region',
 'Start_Year',
 'End_Year',
 'Duration_in_years',
 'Status',
 'Primary_Country',
 'Pre_War_Unemployment_%',
 'During_War_Unemployment_%',
 'Unemployment_Spike_Percentage_Points',
 'Most_Affected_Sector',
 'Youth_Unemployment_Change_%',
 'Pre_War_Poverty_Rate_%',
 'During_War_Poverty_Rate_%',
 'Poverty_Rate_Spike_%',
 'Extreme_Poverty_Rate_%',
 'Food_Insecurity_Rate_%',
 'Households_Fallen_Into_Poverty_Estimate',
 'GDP_Change_%',
 'Inflation_Rate_%',
 'Currency_Devaluation_%',
 'Cost_of_War_USD',
 'Estimated_Reconstruction_Cost_USD',
 'Informal_Economy_Size_Pre_War_%',
 'Reconstruction_Cost_Ratio_USD',
 'Informal_Economy_Size_During_War_%',
 'Black_Market_Activity_Level',
 'Informal_Economy_Size_Spike_%',
 'Primary_Black_Market_Goods',
 'Currency_Black_Market_Rate_Gap_%',
 'War_Profiteering_Documented',
 'Informal_Economy_Size_Spike_Percentage']